from faker import Faker
#object creation 
fk=Faker()
#fake name
# print(fk.name())
# print(fk.email())
# print(fk.address())
# print(fk.url())
# print(fk.century())
# print(fk.first_name())
# print(fk.csv())
# print(fk.cryptocurrency())
# print(fk.file_extension())
# print(fk.job())
# print(fk.month())
# print(fk.paragraph())
# print(fk.language_name())
# print(fk.words())
# print(fk.last_name)
# print(fk.random_letter())
# print(fk.sentences())
# print(fk.profile())
# Faker.seed(1)
# print(fk.profile())
# fk=Faker('hi-IN')
# print(fk.name())
fk=Faker('hi-IN')
print(fk.name())
print(fk.country())
print(fk.address())
